#!/bin/bash
set -e

case "$1" in 
	remove|upgrade)
	if [ -f "/etc/gdm3/Init/Default" ] ; then
		if  grep -q 'detect-resolution' /etc/gdm3/Init/Default ; then
			sed -i '/detect-resolution.*/d' "/etc/gdm3/Init/Default"
		echo "exit 0" >> "/etc/gdm3/Init/Default"
		fi
	fi

	if [ -f "/etc/gdm3/greeter.gsettings" ] ; then
        # Uncomment logo stuff in debian greeter.gsettings
		for exp in  logo fallback-logo ; do
			if grep -q ^"#${exp}" /etc/gdm3/greeter.gsettings ; then
				sed  -i  "s@^#${exp}@${exp}@" /etc/gdm3/greeter.gsettings
			fi
		done 
		if grep -q  ^"#\[org.gnome.login-screen\]" /etc/gdm3/greeter.gsettings ; then
			sed -i "s@^#\[org.gnome.login-screen\]@[org.gnome.login-screen]@" /etc/gdm3/greeter.gsettings
		fi
	fi

	if [ -f "/etc/lightdm/lightdm.conf" ] ; then
		sed -i "s@display-setup-script=.*@\#display-setup-script=@" "/etc/lightdm/lightdm.conf"
	fi

	if [ -f "/etc/slim.conf" ] ; then
		sed -i "s@sessionstart_cmd.*@\# sessionstart_cmd	some command@" "/etc/slim.conf"
	fi

	if [ -f "/etc/kde4/kdm/Xsetup" ] ; then
		if grep -q 'detect-resolution' /etc/kde4/kdm/Xsetup ; then
			sed -i '/detect-resolution.*/d' "/etc/kde4/kdm/Xsetup"
		fi
	fi
	;;
	*)
	echo "postinst called with unknown argument '$1'" >&2
	exit 1
	;;
esac
